import { Class, SubjectCode, User, UserWithClasses } from "../types";

export const users: User[] = [
  {
    uuid: "1",
    firstName: "Adam",
    lastName: "Kowalski",
    age: 16,
    email: "adam.kowalski@example.com",
    phone: "555-123-456",
    avatar: "https://avatars.dicebear.com/api/avataaars/1.svg",
  },
  {
    uuid: "2",
    firstName: "Anna",
    lastName: "Nowak",
    age: 15,
    email: "anna.nowak@example.com",
    phone: "555-987-654",
    avatar: "https://avatars.dicebear.com/api/avataaars/2.svg",
  },
  {
    uuid: "3",
    firstName: "Jan",
    lastName: "Nowicki",
    age: 17,
    email: "jan.nowicki@example.com",
    phone: "555-555-555",
    avatar: "https://avatars.dicebear.com/api/avataaars/3.svg",
  },
  {
    uuid: "4",
    firstName: "Maria",
    lastName: "Kwiatkowska",
    age: 16,
    email: "maria.kwiatkowska@example.com",
    phone: "555-321-654",
    avatar: "https://avatars.dicebear.com/api/avataaars/4.svg",
  },
  {
    uuid: "5",
    firstName: "Adam",
    lastName: "Nowak",
    age: 18,
    email: "adam.nowak@example.com",
    phone: "555-123-456",
    avatar: "https://avatars.dicebear.com/api/avataaars/5.svg",
  },
  {
    uuid: "6",
    firstName: "Katarzyna",
    lastName: "Czajkowska",
    age: 17,
    email: "katarzyna.czajkowska@example.com",
    phone: "555-987-654",
    avatar: "https://avatars.dicebear.com/api/avataaars/6.svg",
  },
  {
    uuid: "7",
    firstName: "Tomasz",
    lastName: "Wojciechowski",
    age: 16,
    email: "tomasz.wojciechowski@example.com",
    phone: "555-456-789",
    avatar: "https://avatars.dicebear.com/api/avataaars/7.svg",
  },
  {
    uuid: "8",
    firstName: "Magdalena",
    lastName: "Jankowska",
    age: 17,
    email: "magdalena.jankowska@example.com",
    phone: "555-789-123",
    avatar: "https://avatars.dicebear.com/api/avataaars/8.svg",
  },
  {
    uuid: "9",
    firstName: "Kamil",
    lastName: "Nowak",
    age: 18,
    email: "kamil.nowak@example.com",
    phone: "555-987-654",
    avatar: "https://avatars.dicebear.com/api/avataaars/9.svg",
  },
  {
    uuid: "10",
    firstName: "Anna",
    lastName: "Wójcik",
    age: 16,
    email: "anna.wojcik@example.com",
    phone: "555-246-810",
    avatar: "https://avatars.dicebear.com/api/avataaars/10.svg",
  },
  {
    uuid: "11",
    firstName: "Jan",
    lastName: "Kowalski",
    age: 17,
    email: "jan.kowalski@example.com",
    phone: "555-369-852",
    avatar: "https://avatars.dicebear.com/api/avataaars/11.svg",
  },
  {
    uuid: "12",
    firstName: "Monika",
    lastName: "Szymańska",
    age: 16,
    email: "monika.szymanska@example.com",
    phone: "555-753-159",
    avatar: "https://avatars.dicebear.com/api/avataaars/12.svg",
  },
  {
    uuid: "13",
    firstName: "Mikołaj",
    lastName: "Kaczmarek",
    age: 18,
    email: "mikolaj.kaczmarek@example.com",
    phone: "555-147-258",
    avatar: "https://avatars.dicebear.com/api/avataaars/13.svg",
  },
  {
    uuid: "14",
    firstName: "Karolina",
    lastName: "Lewandowska",
    age: 17,
    email: "karolina.lewandowska@example.com",
    phone: "555-852-963",
    avatar: "https://avatars.dicebear.com/api/avataaars/14.svg",
  },
  {
    uuid: "15",
    firstName: "Michał",
    lastName: "Piotrowski",
    age: 16,
    email: "michal.piotrowski@example.com",
    phone: "555-369-147",
    avatar: "https://avatars.dicebear.com/api/avataaars/15.svg",
  },
];

export const classes: Class[] = [
  {
    uuid: "1",
    name: "Angielski",
    teacher: {
      uuid: "5",
      firstName: "John",
      lastName: "Doe",
      age: 32,
      email: "john.doe@example.com",
      avatar: "https://avatars.dicebear.com/api/avataaars/5.svg",
      phone: "555-111-222",
    },
    subject: SubjectCode.ENGLISH,
    students: users.slice(0, 2),
  },
  {
    uuid: "2",
    name: "Język Polski",
    teacher: {
      uuid: "6",
      firstName: "Magda",
      lastName: "Kaczmarek",
      age: 29,
      email: "magda.kaczmarek@example.com",
      avatar: "https://avatars.dicebear.com/api/avataaars/6.svg",
      phone: "555-333-444",
    },
    subject: SubjectCode.POLISH,
    students: users.slice(1, 3),
  },
  {
    uuid: "3",
    name: "Historia Świata",
    teacher: {
      uuid: "7",
      firstName: "Peter",
      lastName: "Smith",
      age: 35,
      email: "peter.smith@example.com",
      avatar: "https://avatars.dicebear.com/api/avataaars/7.svg",
      phone: "555-555-666",
    },
    subject: SubjectCode.HISTORY,
    students: users.slice(2),
  },
  {
    uuid: "4",
    name: "Matematyka",
    teacher: {
      uuid: "8",
      firstName: "Linda",
      lastName: "Johnson",
      age: 28,
      email: "linda.johnson@example.com",
      avatar: "https://avatars.dicebear.com/api/avataaars/8.svg",
      phone: "555-777-888",
    },
    subject: SubjectCode.MATH,
    students: users.slice(0, 3),
  },
  {
    uuid: "5",
    name: "Biologia",
    teacher: {
      uuid: "9",
      firstName: "Karen",
      lastName: "Williams",
      age: 33,
      email: "karen.williams@example.com",
      avatar: "https://avatars.dicebear.com/api/avataaars/9.svg",
      phone: "555-999-000",
    },
    subject: SubjectCode.BIOLOGY,
    students: users.slice(1),
  },
  {
    uuid: "6",
    name: "Hiszpański",
    teacher: {
      uuid: "10",
      firstName: "Juan",
      lastName: "Garcia",
      age: 30,
      email: "juan.garcia@example.com",
      avatar: "https://avatars.dicebear.com/api/avataaars/10.svg",
      phone: "555-222-333",
    },
    subject: SubjectCode.SPANISH,
    students: users.slice(0, 2),
  },
  {
    uuid: "7",
    name: "Chemia",
    teacher: {
      uuid: "11",
      firstName: "David",
      lastName: "Brown",
      age: 27,
      email: "david.brown@example.com",
      avatar: "https://avatars.dicebear.com/api/avataaars/11.svg",
      phone: "555-444-555",
    },
    subject: SubjectCode.CHEMISTRY,
    students: users.slice(2),
  },
];

export const userWithClasses: UserWithClasses[] = users.map((user) => ({
  ...user,
  classes: classes.filter((classItem) =>
    classItem.students.some((student) => student.uuid === user.uuid)
  ),
}));
